name: "Cloud.gov CF CLI Tools"
description: "Deploy and manage apps on cloud.gov"
inputs:
  cf_api:
    description: "Target API endpoint. Defaults to api.fr.cloud.gov."
    required: false
  cf_username:
    description: "Username for API authentication"
    required: true
  cf_password:
    description: "Password for API authentication"
    required: true
  cf_docker_password:
    description: "Password for Docker registry authentication"
    required: false
  cf_org:
    description: "Target organization"
    required: true
  cf_space:
    description: "Target space"
    required: true
  cf_manifest:
    description: "Manifest file name to use for pushing. Defaults to 'manifest.yml'."
    required: false
  cf_vars_file:
    description: "Name of the vars file to use"
    required: false
  cf_command:
    description: "CF CLI subcommand to run. Mutually exclusive with 'command:'."
    required: false
  command:
    description: "Command to run. Mutually exclusive with other commands"
    required: false
  liquibase_docker_command:
    description: "Runs liquibase by using already deployed app (deploy_app_from_config_command).  Mutually exclusive with other commands"
    required: false
  deploy_app_from_config_command:
    description: "Deploys app in stopped state. The app could be used to run jobs. Mutually exclusive with other commands"
    required: false
  service_command: 
    description: "Deploys service and waits for service to complete. Mutually exclusive with other commands"
    required: false
  user_service_command: 
    description: "Deploys user service from the file"
    required: false
  user_service_name: 
    description: "Name of the users service"
    required: false    
  database_name: 
    description: "Database to be used by liquibase job"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
